### ISSUE TITLE
关于chatGPT回复，代码块的方式无法复制内容！

### ISSUE THREAD

**Issue by dsssok** [matthaigh27/ChatGPT-android-app#13]
chatGPT回复示列代码时，会以代码块的方式回复：
```
//我是代码
```
这时会有一个代码框，在浏览器点击复制按钮是可以直接复制代码的。
但你的chatGPT应用不支持复制代码块的内容！能否让应用支持那个复制功能？

**Comment by matthaigh27** [comment]
Turns out that isn't a real permission.. Had to implement a javascript hack but seems to work well. Thanks for finding this. See latest release.
