### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by q-dev-1** [matthaigh27/ChatGPT-android-app#3]
When we try to install it, it has there was a problem passing the package.

**Comment by matthaigh27** [comment]
@q-dev-1 What's your device and android version?

**Comment by Vraell** [comment]
Same for me, Oneplus 6t, Android 11

**Comment by q-dev-1** [comment]
> @q-dev-1 What's your device and android version?

Vivo y11 with Android 11

**Comment by matthaigh27** [comment]
Can this be tested on version 1.2? I don't have an android 11 device to test :(

**Comment by Vraell** [comment]
It now works! Thanks.
