### ISSUE TITLE
Keyboard (SwiftKey) Issue?

### ISSUE THREAD

**Issue by Aerasyn** [matthaigh27/ChatGPT-android-app#5]
Seems like this app is the only one on my phone that doesnt allow my keyboard to use it's autocorrect/autocomplete features. This creates a scenario where I make many typos and have to hit backspace to correct things or type so slow that its frustrating. Is there a way to integrate and use these functions? I thought they were built in to the keyboard but its being suppressed? Or do you need to make explicit calls to that function?

**Comment by matthaigh27** [comment]
Should be fixed in latest release
