### ISSUE TITLE
登录界面刷新

### ISSUE THREAD

**Issue by blue340** [matthaigh27/ChatGPT-android-app#8]
我来自中国，目前无法直接使ChatGPT，但是借助VPN使用，但是需要再登录失败页面刷新一下，如果您能在登录界面设置一个刷新按钮就好了

**Comment by matthaigh27** [comment]
From google translate:
> I’m from China, and I can’t use ChatGPT directly at present, but I can use it with the help of a VPN, but I need to refresh the login failure page. It would be great if you could set a refresh button on the login interface

@blue340 How come you need to refresh on the login page? Why does starting the VPN before booting the app not work? Perhaps that needs fixing instead.

**Comment by dsssok** [comment]
> 我來自中國，目前無法直接使用ChatGPT，但是是藉VPN使用，但需要重新登錄失敗頁面刷新一下，如果您能在登錄界面就設置甩了一個刷

我也来自中国，挂VPN出现断开是VPN的问题，重回登录面是因为chatGPT的IP验证造成的！换VPN吧。有的VPN很稳定的，我挂台湾的就很稳定。

**Comment by matthaigh27** [comment]
Tried fixing this as best as I could, the swipe to refresh wouldn't play nicely with the chatGPT interface, so its only available on the login pages. See latest release.
